In [15]:
import torch
import numpy as np

In [69]:
x = torch.tensor([[1,2,3],[3,4,5]])
x

tensor([[1, 2, 3],
        [3, 4, 5]])

In [90]:
x = np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [95]:
from typing import Any, List, Tuple
def shape(ls: Any) -> List[int]:
    if isinstance(ls, (list, tuple)):
        return [len(ls)] + shape(ls[0])
    else:
        return []

In [97]:
shape([5,2,3])

[3]

In [99]:
ls = [5,2,3]
shape(ls[0])

[]

In [85]:
from datetime import date
 
 
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age
 
    # a class method to create a Person object by birth year.
    @classmethod
    def fromBirthYear(cls, name, year):
        print(cls)
        print('myang')
        return cls(name, date.today().year - year)
 
    # a static method to check if a Person is adult or not.
    @staticmethod
    def isAdult(age):
        return age > 18
 
 
person1 = Person('mayank', 21)
person2 = Person.fromBirthYear('mayank', 1996)

<class '__main__.Person'>
myang


In [82]:
arr = np.array([1, 2, 3])
len(arr)

3

In [25]:
for element in arr:
    print(element)

[1 2 3]
[4 5 6]


In [27]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
def strides_from_shape(shape):
    layout = [1]
    offset = 1
    for s in reversed(shape):
        layout.append(s * offset)
        offset = s * offset
    return tuple(reversed(layout[:-1]))

strides_from_shape([3,5,2])

(10, 2, 1)

In [68]:
import random
tuple(random.randint(0, s - 1) for s in (2,3))

(1, 2)

In [54]:
aindex = np.array((2,1))
aindex

array([2, 1])

In [56]:
aindex.shape[0]

2